/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    `maven-publish`
     application
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    implementation("com.squareup.okhttp3:okhttp:4.9.0")
    implementation("com.googlecode.json-simple:json-simple:1.1.1")
    implementation("org.testng:testng:6.9.10")
    //The dependency also uses the google guava library
    implementation("com.google.guava:guava:30.0-jre")
}

group = "groupId"
version = "1.0-SNAPSHOT"
description = "contemporary-software-development-ca2-2021-22-team-project-team-4"


publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

application{
    //Define the main class for the application
    mainClass.set("PortfolioSystem.Main")
}

tasks.named<Test>("test") {
    useTestNG()
}

java {
       withJavadocJar()
}

 extensions.findByName("buildScan")?.withGroovyBuilder {
    setProperty("termsOfServiceUrl", "https://gradle.com/terms-of-service")
    setProperty("termsOfServiceAgree", "yes")
}
